config/routes.rb
Elrecetario::Application.routes.draw do

  resources :users

  resource :sessions, only: [:new,:create,:destroy]

  resources :heads

  resources :tricks

  resources :competitions
  get "recipes/filtrado" => 'recipes#filtrado'

  resources :recipes do
    resources :comments
  end
  resources :comments
  root "heads#index"

  get '/login' => "sessions#new", as: "login"
  get '/logout' => "sessions#destroy", as: "logout"
  get '/signin' => "users#new", as: "signin"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to  :users
  belongs_to  :recipes
end

app/models/competition.rb
class Competition < ActiveRecord::Base
end

app/models/head.rb
class Head < ActiveRecord::Base
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

   #include ActionController::MimeResponds
   #scope :filtrado, lambda{|ingrediente| where("recipes.ingrediente LIKE ?", "%#{val}%")}

  has_many  :comments

  def self.search(val)
    if val[:ingrediente] != "" and val[:plato] != "" and val[:dificultad] != ""
      where("ingrediente = ? and plato = ? and dificultad = ?", "#{val[:ingrediente]}","#{val[:plato]}","#{val[:dificultad]}")
    elsif val[:ingrediente] != "" and val[:plato] != ""
      where("ingrediente = ? and plato = ?", "#{val[:ingrediente]}","#{val[:plato]}")
    elsif val[:ingrediente] != "" and val[:dificultad] != ""
      where("ingrediente = ? and dificultad = ?", "#{val[:ingrediente]}","#{val[:dificultad]}")
    elsif val[:plato] != "" and val[:dificultad] != ""
      where("plato = ? and dificultad = ?","#{val[:plato]}","#{val[:dificultad]}")
    elsif val[:ingrediente] != ""
      where("ingrediente = ?", "#{val[:ingrediente]}")
    elsif val[:plato] != ""
      where("plato = ?","#{val[:plato]}")
    elsif val[:dificultad] != ""
       where("dificultad = ?", "#{val[:dificultad]}")
    end
  end
end

app/models/trick.rb
class Trick < ActiveRecord::Base
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  validates :usuario, format: {with: /[a-zA-Z]+[-0-9.+_*]/, message: "Formato de nombre de usuario no válido"}
  validates :password, length: {in: 6..18}, confirmation: true

  has_many  :comments
  
  before_save :encrypt_new_password

  def self.authenticate(usuario,pass)
    user = find_by_usuario(usuario)
    return user if user && user.authenticated?(pass)
  end

  def authenticated?(pass)
    self.password == encrypt(pass)
  end

  protected
    def encrypt_new_password
      return if password.blank?
      self.password = encrypt(password)
    end
    
    def encrypt(string)
      Digest::SHA1.hexdigest(string)
    end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  protected
    def current_user
      return unless session[:user_id]
      @current_user ||= User.find_by_id(session[:user_id])
    end
    
    helper_method :current_user

    def authenticate
      logged_in? || access_denied
    end

    def logged_in?
      current_user.is_a? User
    end

    helper_method :logged_in?

    def access_denied
      redirect_to login_path, notice: "Please login in to continue" and false
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_recipe
  before_action :authenticate
  def create
    @comment = @recipe.comments.new(comment_params)
    if @comment.save
      redirect_to @recipe, notice: 'Thanks for you comment'
    else
      redirect_to @recipe, alert: 'Unable to add comment'
    end
  end

private
  def load_recipe
    @recipe = Recipe.find_by_id(params[:recipe_id])
  end
  def comment_params
    params.require(:comment).permit(:name, :body)
  end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController

  # GET /competitions
  # GET /competitions.json
  def index
    @competitions = Competition.first(2)
    @competiti= "seleccionado"
  end


  
end

app/controllers/heads_controller.rb
class HeadsController < ApplicationController

  # GET /heads
  # GET /heads.json
  def index
      @home= "seleccionado"
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.last(3)
    @recip= "seleccionado"
    
  end

  def filtrado
    @recipes = Recipe.search(params)
    respond_to do |format|
      format.js 
    end
    
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
     @recip= "seleccionado"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  

  def create
    if user= User.authenticate(params[:usuario],params[:password])
      session[:user_id]=user.id
      redirect_to root_path, notice: 'Logged in succsessfully'
    else
      flash.now[:alert] = "invalid usuario/password combination"
      render :new    
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'logged out successfully'
  end
end

app/controllers/tricks_controller.rb
class TricksController < ApplicationController
  before_action :set_trick, only: [:show, :edit, :update, :destroy]

  # GET /tricks
  # GET /tricks.json
  def index
    @tricks = Trick.first(6)
    @tric= "seleccionado"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)  
      if @user.save
        redirect_to root_path, notice: 'Usuario creado satisfactoriamente'
      else
        render action: :new
      end    
  end

  private
    def set_user
      @user = current_user
    end

    def user_params
      params.require(:user).permit(:usuario, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/helpers/heads_helper.rb
module HeadsHelper
end

app/helpers/principal_helper.rb
module PrincipalHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tricks_helper.rb
module TricksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %> 
  <%= comment.body %>
<% end %>

app/views/comments/new.html.erb
<%= form_for([@recipe,@recipe.comments.new]) do|f| %>
  
  <% if logged_in? %>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit 'add' %>
  </div>
  <% else %>
     <%= link_to "Regístrate", "/signin" %>
		 <%= link_to "Login", "/login" %>
  <% end %>
<% end %>

app/views/competitions/_competitions.html.erb
<% @competitions.each do |competition| %>
			<div class="grid_9 concurso">
				<%= image_tag competition.imagen %>
			</div>
<% end %>

app/views/competitions/index.html.erb
<% content_for :head do %>
<%= stylesheet_link_tag    "competitions", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag 'competitions' %>
<% end %>
<div class="grid_3 containerSubmenu">
      <script type="text/javascript">
        comun();
      </script>
			<div class="grid_3 alpha">

				<div id="radioset" >
					<div id="accordion">

						<h3>comunidades</h3>

						<div id="divs">
							<form name="comunidade" onclick="showHint()" >
	
								<input type="radio" id="radio1" name="comunidades" value="canarias" >
									<label for="radio1" id="radius">
										canarias
									</label><br>
								<input type="radio" id="radio2" name="comunidades" value="madrid">
									<label for="radio2">
										madrid
									</label>
								<input type="radio" id="radio3" name="comunidades" value="cataluña" >
									<label for="radio3" id="radius">
										cataluña
									</label><br>
								<input type="radio" id="radio4" name="comunidades" value="andalucia" >
									<label for="radio4" id="radius">
										andalucia
									</label><br>
	
							</form>
						</div>	
					</div>
				</div>
			</div>
		</div>

<div class="grid_9 omega container" id="resultado">
  <%= render partial: "competitions" %>
</div>

app/views/heads/index.html.erb
<% content_for :head do %>
<%= stylesheet_link_tag    "heads", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag 'heads' %>
<%end%>
<div class="container">
      <script type="text/javascript">
        comun();
      </script>
			<div id="grid_12 contenidos">
				<div class="opcion1">
					<div class="grid_5 alpha model2">
						<a href="receta.html"><%= image_tag "roscon.jpg" %></a>
					</div>
					<div class="grid_7 omega model2">
						<a href="receta.html"><h3>Roscón de Reyes</h3></a>
						<p>Sorprende a los tuyos en navidades con un delicioso Roscón de Reyes Casero.</p>
					</div>
				</div>
				
 
				<div class="opcion2">
					<div class="grid_5 alpha model2">
						<a href="receta.html"><%= image_tag "pescado.jpg" %></a>
					</div>
					<div class="grid_7 omega model2">
						<a href="receta.html"><h3>Salmón al horno</h3></a>
						<p>Prepárate este plato tan sano y delicioso al mismo tiempo.</p>
					</div>
				</div>
 
				<div class="opcion3">
					<div class="grid_5 alpha model2">
						<a href="receta.html"><%= image_tag "tarta.jpg" %></a>
					</div>
					<div class="grid_7 omega model2">
						<a href="receta.html"><h3>Tarta de 3 chocolates</h3></a>
						<p>¿Qué mejor que una tarta de 3 chocolates para endulzarte en un día especial?</p>
					</div>
				</div>
			</div>
			<div class="grid_1 menu_slider">
				<ul id="icons" class="ui-widget ui-helper-clearfix">
					<li class="ui-state-default ui-corner-all next" title=".ui-icon-arrowthick-1-e"><span class="ui-icon ui-icon-arrowthick-1-e"></span></li>
					<li class="ui-state-default ui-corner-all prev" title=".ui-icon-arrowthick-1-w"><span class="ui-icon ui-icon-arrowthick-1-w"></span></li>
				</ul>
				
			</div>

			
		</div>
		<div class="clear"></div>
		<div class="efect container">
			<div class="grid_2 alpha model1" id="left">
				<%= image_tag("tartaleta.jpg", :class => "image") %></br>
				<a href="receta.html">Receta1</a>
			</div>
			<div class="grid_2 model1 center">
				<%= image_tag("carne.jpg", :class => "image") %></br>
				<a href="receta.html">Receta2</a>
			</div>
			<div class="grid_2 model1 center">
				<%= image_tag("verduras.jpg", :class => "image") %></br>
				<a href="receta.html">Receta3</a>
			</div>
			<div class="grid_2 model1 center">
				<%= image_tag("chocolate.jpg", :class => "image") %></br>
				<a href="receta.html">Receta4</a>
			</div>
			<div class="grid_2 omega model1" id="right">
				<%= image_tag("pasta.jpg", :class => "image") %></br>
				<a href="receta.html">Receta5</a>
			</div>
		</div>
		<div class="clear"></div>

app/views/recipes/_recipes.html.erb
<% @recipes.each do |recipe| %>
	<div class='container2'>
			<div class='grid_3 alpha imgRecetas'>
        <%= link_to image_tag(recipe.imagen), recipe %>
      </div>
      <div class='grid_6 prefix_3 omega model2'>
        <h1> <%= link_to recipe.titulo, recipe %> </h1>
        <p> <%= recipe.datos %> </p>
      	<div class='grid_6'>
				  <a class='grid_2 comentar' href='#'>Coméntala</a>
					<div class='grid_2 twitter'>
					  <a href="https://twitter.com/share" data-text="Holaaa" class="twitter-share-button" data-         lang="en">Tweet</a>
            <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
					</div>
					<div class='grid_2 facebook'>
						<iframe src="http://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2FElRecetario&amp;width&amp;layout=button_count&amp;action=like&amp;show_faces=false&amp;share=false&amp;height=35"></iframe>
					</div>
        </div>
      </div>
	</div>
  <% end %>

app/views/recipes/filtrado.js.erb
$("#resultado").html("<%= escape_javascript render( partial: "recipes") %>");

app/views/recipes/index.html.erb
<% content_for :head do %>
<%= stylesheet_link_tag    "recipes", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag 'recipes' %>
<%end%>
<div class="grid_3 containerSubmenu">
      <script type="text/javascript">
        comun();
      </script>
			<div class="grid_3 alpha">

				<div id="radioset" >
					<div id="accordion">
            <h3>Ingredientes</h3>

						<div id="divs">
            <form name="ingredientes"  onclick="showHint()">
								<input type="radio" id="radio1" name="ingrediente" value="pescado" >
									<label for="radio1">
										pescado
									</label><br>
								<input type="radio" id="radio2" name="ingrediente" value="chocolate">
									<label for="radio2">
										chocolate
									</label>
                <input type="radio" id="radio3" name="ingrediente" value="verduras">
									<label for="radio3">
										verduras
									</label>
	
							</form>
						</div>
						<h3>Dificultad</h3>
						<div id="divs" >
							<form name="dificultad"  onclick="showHint()">
								<input type="radio" id="radio4" name="dificulta" value="facil">
									<label for="radio4" >
										facil
									</label></br>
								<input type="radio" id="radio5" name="dificulta" value="media">
									<label for="radio5" >				
										media
									</label><br>
								<input type="radio" id="radio6" name="dificulta" value="alta">
								<label for="radio6" >
									alta
								</label>
							</form>
						</div>

						<h3>Plato</h3>
						<div id="divs">
							<form name="platos"  onclick="showHint()">
								<input type="radio" id="radio7" name="plato" value="principal" >
									<label for="radio7" >
											principal
									</label><br>
								<input type="radio" id="radio8" name="plato" value="postre" >
									<label for="radio8" >
											postre
									</label>
							</form>
             </div>
						
					</div>
				</div>

			</div>
</div>
<div class="grid_9 omega container" id="resultado">
  <%= render partial: "recipes" %>
</div>

		

app/views/recipes/show.html.erb
<% content_for :head do %>
<%= stylesheet_link_tag    "one_recipes", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag 'one_recipes' %>
<style>
	#icons {
	margin: 0;
	padding: 0;
}
#icons li {
	margin: 2px;
	position: absolute;
	padding: 4px 0;
	cursor: pointer;
	list-style: none;
}
#icons span.ui-icon {
	margin: 0 4px;
}
</style>
<%end%>
		<div class="grid_12 model3Titulo">
			<h1 id="tituloReceta"><%= @recipe.titulo %></h1> 		 
		</div>
		<div class="clear"></div>
		<div class="grid_4 alpha">
			<div class="grid_4 model3">
				<h2 id="tituloIngr">Ingredientes</h2>
				<%= @recipe.ingredientes %>
			</div>
		<div class="grid_4">
			<h2 id="tituloClaves">Claves de la receta</h2>
			<%= @recipe.datos %>
			<div class="grid_4">
				<a class="grid_1 comentar" href="#">Coméntala</a>
			
				<div class="grid_1 twitter">
					<a href="https://twitter.com/share" data-text="Holaaa" class="twitter-share-button" data-lang="en">Tweet</a>
          <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
				</div>
					
			</div>
			<div class="grid_2 facebook">
					<iframe src="http://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2FElRecetario&amp;width&amp;layout=button_count&amp;action=like&amp;show_faces=false&amp;share=false&amp;height=35" ></iframe>
			</div>
		</div>
		</div>


		<div class="grid_8 omega">
			<div class="grid_8 model3">
				
				<ul id="icons" class="ui-widget ui-helper-clearfix">
					<li class="ui-state-default ui-corner-all" title=".ui-icon-play"><span class="ui-icon ui-icon-play"></span></li>
				</ul>
				<%= image_tag @recipe.imagen, class: "visible", id: "imgvide" %>
				<%= video_tag @recipe.video, class: "oculto", id: "vid",width: '500', height: '360', controls: true %>
			</div>
		
		<div class="clear"></div>	
			<div class="grid_7 model3">
				<h2 id="tituloPreparacion">Preparación de la receta</h2>
				<%= @recipe.descripcion %>
			</div>
		</div>
		<div class="clear"></div>	
		
		<div onclick="show()">
			<dl>
				<dt>Mira lo que comentan de la receta</dt>
				<dd><ul>
					<div id="resultado"></div>
					<li type="circle">
              <h3>Comenta la receta</h3>
              <div id="comments">
                <%= render @recipe.comments %>
              </div>
                <%= render file: 'comments/new' %>
					</li>
				</ul></dd>
			</dl>
		</div>

app/views/tricks/_tricks.html.erb
 <% @tricks.each do |trick| %>
			<div class="grid_4 alpha model3">
        <%= image_tag trick.imagen %>
      </div>
			<div class="grid_6 prefix_2 omega model3">
        <a href="#"><h1><%= trick.titulo %></h1></a>
        <p><%= trick.informacion %></p>
      </div>
<% end %>

app/views/tricks/index.html.erb
<% content_for :head do %>
<%= stylesheet_link_tag    "tricks", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag 'tricks' %>
<%end%>
<div class="grid_3 containerSubmenu">
      <script type="text/javascript">
        comun();
      </script>
			<div class="grid_3 alpha">
			<div id="radioset" >
					<div id="accordion">

						<h3>comunidades</h3>

						<div id="divs">
							<form name="sabiasque"  onclick="showHint()">
	
								<input type="radio" id="radio1" name="sabias" value="trucos" >
									<label for="radio1" id="radius">
										Trucos de cocina
									</label><br>
								<input type="radio" id="radio2" name="sabias" value="info">
									<label for="radio2">
										Informacion nutricional
									</label>
								<input type="radio" id="radio3" name="sabias" value="cocineros" >
									<label for="radio3" id="radius">
										Cocineros profecionales
									</label><br>
								<input type="radio" id="radio4" name="sabias" value="premios" >
									<label for="radio4" id="radius">
										Premios de cocinas
									</label><br>
	
							</form>
						</div>


						
					</div>
				</div>
			</div>
		</div>

<div class="grid_9 omega container" id="resultado">
      <%= render partial: "tricks" %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usuario %><br>
    <%= f.text_field :usuario %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<div align="center">
</br></br>
<h1>Regístrate</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>
</div>